### PR TITLE
Create Analytics Window for Parking Lot Occupancy

### LINKED ISSUE #46: Create Analytics Window for the Application
- Create a graphical representation of the occupancy at parking spaces at a timely basis
- Make API calls to retrieve analytics information

### LINKED ISSUE #54: Netlify Deployment Issue
Netlify Deployment Previews are failing to build due to the following errors in the codebase

Error Log

7:43:37 PM: [eslint]
7:43:37 PM: src/Analytics.js
7:43:37 PM: Line 57:12: 'spotNum' is assigned a value but never used no-unused-vars
7:43:37 PM: src/App.js
7:43:37 PM: Line 7:8: 'Dropdown' is defined but never used no-unused-vars
7:43:37 PM: src/components/CustomBar.js
7:43:37 PM: Line 3:1: Block is redundant no-lone-blocks

I will be fixing them

### PR DESCRIPTION
**Pull request by Kabishan**
This PR resolves issue #46 

Image
image

Feedback is appreciated.

### CODE REVIEW

**Comment by almen-ng** [comment]
@Kabishan would you be able to check the deploy log on netlify

**Comment by Kabishan** [comment]
@almen-ng 

Sure, I'll report my findings here. I believe the deployment has been failing for some time now.

**Comment by Kabishan** [comment]
Error Log

7:43:37 PM: [eslint]
7:43:37 PM: src/Analytics.js
7:43:37 PM:   Line 57:12:  'spotNum' is assigned a value but never used  no-unused-vars
7:43:37 PM: src/App.js
7:43:37 PM:   Line 7:8:  'Dropdown' is defined but never used  no-unused-vars
7:43:37 PM: src/components/CustomBar.js
7:43:37 PM:   Line 3:1:  Block is redundant  no-lone-blocks

I've made a commit to fix these issues

**Comment by Kabishan** [comment]
@almen-ng Netlify Deployment Issue resolved.

**Review by almen-ng — APPROVED** [review]
lgtm

I'm assuming we'll be reading the json obj for the history and calculating the total once the backend is implemented.

good work!!! 😁

**Comment by Kabishan** [comment]
@almen-ng
Yes, that's correct. We may need to somewhat manipulate the back end data, but the front end implementation is good to go.

**Pull request merged**
